connection:
  host: localhost
  port: 5672
  username: proctoring-bot
  password: proctoring-bot

queues:
  proctoring-queue:
    exchange: proctoring-exchange
    exchange_type: direct
    routing_key: proctoring-bot
    queue_name: proctoring-queue
    durable: true
    prefetch_count: 1
  processing-service-queue:
    exchange: processing-service-exchange
    exchange_type: direct
    routing_key: processing-service
    queue_name: processing-service-queue
    durable: true
    prefetch_count: 1

minio:
  endpoint: localhost:9000
  access_key: proctoring-bot
  secret_key: proctoring-bot
  secure: false
  bucket: proctoring-files