connection:
  host: localhost
  port: 5672
  username: proctoring-bot
  password: proctoring-bot

queues:
  proctoring_queue:
    exchange: proctoring-exchange
    exchange_type: direct
    routing_key: proctoring-bot
    queue_name: proctoring-queue
    durable: true
    prefetch_count: 1

minio:
  endpoint: localhost:9000
  access_key: proctoring-bot
  secret_key: proctoring-bot
  secure: false
  bucket: proctoring-files