services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=proctoring-bot
      - RABBITMQ_DEFAULT_PASS=proctoring-bot
    ports:
      - "5672:5672"  
      - "15672:15672"
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: proctoring_bot_minio
    restart: always
    environment:
      MINIO_ROOT_USER: proctoring-bot
      MINIO_ROOT_PASSWORD: proctoring-bot
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    volumes:
      - minio_data:/data

volumes:
  rabbitmq_data:
  minio_data:
